export const LANAGUAGES_LIST = {
  FRENCH: 'Français',
  ARABIC: 'العربية',
  ENGLISH: 'English',
};

export const LANGUAGES_ARRAY = [
  {
    name: LANAGUAGES_LIST.ARABIC,
    image: require('../assests/languages/arabic.png'),
  },
  {
    name: LANAGUAGES_LIST.FRENCH,
    image: require('../assests/languages/french.png'),
  },
  {
    name: LANAGUAGES_LIST.ENGLISH,
    image: require('../assests/languages/english.png'),
  },
];

export const LANGUAGES = {
  AR: {
    CHOOSE_LANGUAGE: 'اختر لغتك',
    NEXT: 'التالي',
    SLIDE1_TITLE: 'آلاف الأطباء',
    SLIDE1_DESCRIPTION:
      'الوصول إلى آلاف الأطباء على الفور. يمكنك بسهولة الاتصال بالأطباء والاتصال باحتياجاتك.',
    SLIDE2_TITLE: 'تحدث مباشرة مع الأطباء',
    SLIDE2_DESCRIPTION:
      'تواصل بسهولة مع الطبيب وابدأ دردشة الفيديو للحصول على علاج ووصفة طبية أفضل.',
    SLIDE3_TITLE: 'مكالمات الفيديو مع الأطباء',
    SLIDE3_DESCRIPTION:
      'احجز موعدًا مع الطبيب ، وتحدث مع الطبيب عبر خطاب الموعد واحصل على استشارة.',
    GET_STARTED: 'ابدأ الآن',
    HOME: 'الصفحة الرئيسية',
    SIGN_IN: 'تسجيل الدخول',
    REGISTER: 'الاشتراك',
    LANGUAGE: 'اللغة',
    LOGIN_AS: 'تسجيل الدخول باسم',
    REGISTER_AS: 'سجل باسم',
    PATIENT: 'زبون',
    DOCTOR: 'طبيب',
    PARAMEDICAL: 'شبه طبي',
    CLINIC_HOSPITAL: 'عيادة / مستشفى',
    LABORATORY: 'مختبر',
    PHARMACY: 'صيدلية',
    AMBULANCE: 'سياره اسعاف',
    BLOOD_DONOR: 'متبرع بالدم',
    PROFESSIONAL: 'مهني',
    WELCOME_BACK: 'مرحبا بعودتك',
    SIGN_IN_TO_CONTINUE: 'سجل الدخول للمتابعة',
    FORGOT_PASSWORD: 'نسيت كلمة السر؟',
    ABOUT: 'من نحن',
    CONTACT: 'تواصلوا معنا',
    FOLLOW: 'تابعونا على',
    EMAIL_PHONE: 'البريد الإلكتروني / الهاتف',
    ENTER_EMAIL_PHONE: 'أدخل بريدك الإلكتروني أو رقم هاتفك',
    INVALID_EMAIL_PHONE: 'البريد الإلكتروني أو رقم الهاتف غير صالح',
    PASSWORD: 'كلمة المرور',
    ENTER_PASSWORD: 'أدخل كلمة المرور',
    INVALID_PASSWORD: 'كلمة المرور غير صالحة',
    CONFIRM_PASSWORD: 'تأكيد كلمة المرور',
    PASSWORD_DONT_MATCH: 'كلمة المرور غير متطابقة',
    SIGNING_IN: 'جاري تسجيل الدخول',
    FIRST_NAME: 'الاسم',
    LAST_NAME: 'اللقب',
    GENDER: 'الجنس',
    DATE_OF_BIRTH: 'تاريخ الميلاد',
    ADDRESS: 'العنوان',
    PHONE: 'رقم الهاتف',
    ENTER_LAST_NAME: 'أدخل لقبك',
    ENTER_FIRST_NAME: 'أدخل أسمك',
    ENTER_ADDRESS: 'أدخل عنوانك',
    ENTER_PHONE: 'أدخل رقم هاتفك',
    ENTER_DATE_OF_BIRTH: 'أدخل تاريخ ميلادك',
    SELECT_GENDER: 'حدد جنسك',
    INVALID_FIRST_NAME: 'اسم غير صالح',
    INVALID_LAST_NAME: 'لقب غير صالح',
    INVALID_ADDRESS: 'عنوان غير صالح',
    INVALID_PHONE: 'رقم الهاتف غير صالح',
    EMAIL: 'البريد الإلكتروني',
    ENTER_EMAIL: 'أدخل عنوان بريدك الالكتروني',
    INVALID_EMAIL: 'عنوان البريد الإلكتروني غير صالح',
    ERROR: 'خطأ',
    ALERT: 'إنذار',
    FILL_THE_FORM: 'يرجى التأكد من إدخال جميع المعلومات الخاصة بك وبشكل صحيح',
    SIGNING_UP: 'جاري التسجيل',
    CONFIRM_EMAIL: 'أكد بريدك الإلكتروني',
    EMAIL_DONT_MATCH: 'عنوان البريد الإلكتروني غير متطابق',
    NAME: 'الاسم',
    INVALID_NAME: 'اسم غير صالح',
    ENTER_NAME: 'أدخل الاسم',
    SPECIALTY: 'التخصص',
    SELECT_SPECIALTY: 'حدد تخصصك',
    INVALID_SPECIALTY: 'تخصص غير صالح',
    ENTER_LOCATION: 'حدد موقعك',
    BUISNESS_IDENTIFIER: 'معرف العمل',
    ENTER_BUISNESS_IDENTIFIER: 'أدخل معرف عملك',
    INVALID_BUISNESS_IDENTIFIER: 'معرّف عمل غير صالح',
    SELECT_CITY: 'حدد ولايتك',
    SELECT_COMMUNE: 'حدد بلديتك',
    SELECT_BLOOD_TYPE: 'حدد فصيلة دمك',
    SIGNING_UP: 'جاري التسجيل',
    SIGN_UP_SUCCESSFUL: 'تم التسجيل بنجاح',
    IN_SEARCH_FOR: 'ابحث عن',
    BOOK_APPOINTMENT: 'حجز موعد',
    NO_RESULTS: 'لم يتم العثور على نتائج',
    SEARCH: 'ابحث',
    ERROR_OCCURED: 'حدث خطأ',
    SIGN_OUT: 'تسجيل الخروج',
    EMAIL_PHONE_IN_USE: 'البريد الإلكتروني أو الهاتف قيد الاستخدام',
    USER_DOESNT_EXIST: 'المستخدم غير موجود',
    WRONG_PASSWORD: 'كلمة مرور خاطئة',
    SEARCHING: 'جاري البحث',
    VIDEO_AVAILABLE: 'استشارة الفيديو متوفرة',
    CONSULTATION_NOT_AVAILABLE: 'الاستشارة غير متوفرة',
    MY_APPOINTMENTS: 'مواعيدي',
    MY_RELATIVES: 'اقاربي',
    MY_FILES: 'ملفاتي',
    PAST: 'المنقضية',
    COMING: 'القادمة',
    CANCELLED: 'الملغاة',
    EDIT: 'تعديل',
    DELETE: 'حذف',
    CANCEL: 'إلغاء',
    ADD: 'أضف',
    ADDING: 'جاري الإضافة',
    ADDED_SUCCESSFULY: 'تمت الاضافة بنجاح',
    REBOOK_APPOINTMENT: 'حجز موعد آخر',
    PRESCRIPTIONS: 'الوصفات الطبية',
    RECORDS: 'السجلات',
    TEST_RESULTS: 'نتائج التحليلات',
    TREATMENTS: 'العلاجات',
    BIOLOGY: 'بيولوجيا',
    REPORTS: 'التقارير',
    RADIOLOGY: 'الصور الطبية',
    VACCINATIONS: 'التطعيمات',
    PRESENTATION: 'تعريف',
    PRICING: 'التسعير',
    TELECONSULTATION: 'الاستشارة عن بعد',
    CABINET: 'مكتب الطبيب',
    EXERCICE_ADDRESS: 'عنوان مكان الممارسة',
    SUNDAY: 'الأحد',
    MONDAY: 'الإثنين',
    TUESDAY: 'الثلاثاء',
    WEDNESDAY: 'الأربعاء',
    THURSDAY: 'الخميس',
    FRIDAY: 'الجمعة',
    SATURDAY: 'السبت',
    WORKING_DAYS: 'أيام العمل',
    DAY: 'اليوم',
    OPENING: 'الافتتاح',
    CLOSING: 'الختام',
    SELECT_APPOINTMENT_TYPE: 'حدد نوع الموعد',
    CONTACT_INFORMATIONS: 'معلومات الاتصال',
    SPOKEN_LANGUAGES: 'يتحدث اللغات',
    CONSULTED_BEFORE: 'هل سبق لك أن تمت استشارتك من قبل هذا الطبيب؟',
    YES: 'نعم',
    NO: 'لا',
    COURSES: 'دورات التكوين',
    APPOINTMENT_TYPE: 'نوع الموعد',
    APPOINTMENT_HOUR: 'ساعة الموعد',
    NO_AVAILABLE_APPOINTMENTS: 'لا توجد مواعيد متاحة',
    MY_PATIENTS: 'مرضاي',
    ADD_RELATIVE: 'إضافة قريب',
    ADD_PATIENT: 'إضافة مريض',
    SUBSCRIPTION: 'الاشتراك',
    PROFILE: 'الملف الشخصي',
    ADD_APPOINTMENT: 'إضافة موعد',
    EDIT_SUBSCRIPTION: 'تعديل الاشتراك',
    EDIT_PROFILE: 'تعديل الملف الشخصي',
    AVAILABLE: 'متوفر',
    MY_INFORMATIONS: 'معلوماتي',
    UPDATING: 'جاري التحديث',
    UPDATED_SUCCESSFULY: 'تم التحديث بنجاح',
    WILAYA: 'الولاية',
    COMMUNE: 'البلدية',
    CONTACT_TEXT:
      'إذا كان لديك سؤال ، فاتصل بنا على عنوان البريد الإلكتروني أدناه',
    SELECT_DOCUMENT_TYPE: 'حدد نوع الملف',
    DESCRIPTION: 'الوصف',
    ENTER_DESCRIPTION: 'أدخل الوصف',
    INVALID_DESCRIPTION: 'وصف غير صالح',
    SELECT_PAYMENT_METHOD: 'اختر طريقة الدفع',
    AMOUNT: 'المبلغ',
    BALANCE: 'الرصيد',
    BANK_CARD: 'بطاقة مصرفية',
    SUBSCRIPTION_INFORMATIONS: 'معلومات الاشتراك',
    SUBSCRIPTION_1: 'التخطيط وإدارة المرضى',
    SUBSCRIPTION_2: 'استشارة بالفيديو',
    VALIDITY: 'الصلاحية',
    BEGIN_DATE: 'تاريخ البداية',
    END_DATE: 'تاريخ الانتهاء',
    REMAINING_DAYS: 'الأيام المتبقية',
    REMAINING_MINUTES: 'الدقائق المتبقية',
    SESSION_DURATION: 'مدة الجلسة',
    NOT_SUBSCRIBED: 'غير مشترك',
    BEGIN_APPOINTMENT: 'ابدأ الجلسة',
    NO_FILES: 'لا توجد ملفات',
    NO_APPOINTMENTS: 'لم يتم العثور على مواعيد',
    APPOINTMENT_BOOKED: 'تم حجز الموعد بنجاح',
    ENTER_APPOINTMENT_DETAILS: 'أدخل جميع تفاصيل الموعد',
  },
  FR: {
    CHOOSE_LANGUAGE: 'Choisissez votre langue',
    NEXT: 'Suivant',
    SLIDE1_TITLE: 'Des milliers de médecins',
    SLIDE1_DESCRIPTION:
      'Accédez à des milliers de médecins instantanément. Vous pouvez facilement contacter les médecins et contacter pour vos besoins.',
    SLIDE2_TITLE: 'Discussion en direct avec des médecins',
    SLIDE2_DESCRIPTION:
      'Connectez-vous facilement avec un médecin et démarrez un chat vidéo pour un meilleur traitement et une meilleure prescription.',
    SLIDE3_TITLE: 'Appels vidéo avec des médecins',
    SLIDE3_DESCRIPTION:
      'Prenez rendez-vous avec un médecin. Discutez avec un médecin via une lettre de rendez-vous et obtenez une consultation.',
    GET_STARTED: 'Commencer',
    HOME: 'Acceuil',
    SIGN_IN: 'Se connecter',
    REGISTER: "S'inscrire",
    LANGUAGE: 'Langue',
    LOGIN_AS: 'Se connecter en tant que',
    REGISTER_AS: "S'inscrire en tant que",
    PATIENT: 'Patient',
    DOCTOR: 'Medecin',
    PARAMEDICAL: 'Paramedical',
    CLINIC_HOSPITAL: 'Clinique/Hopital',
    LABORATORY: 'Laboratoire',
    PHARMACY: 'Pharmacie',
    AMBULANCE: 'Ambulance',
    BLOOD_DONOR: 'Donneur de sang',
    PROFESSIONAL: 'Professionel',
    WELCOME_BACK: 'Bienvenue à nouveau!',
    SIGN_IN_TO_CONTINUE: 'Connectez vous pour continuer.',
    FORGOT_PASSWORD: 'Mot de passe oublie?',
    ABOUT: 'A propos de nous',
    CONTACT: 'Contactez nous',
    FOLLOW: 'Suivez nous sur',
    EMAIL_PHONE: 'Email / Téléphone',
    ENTER_EMAIL_PHONE: 'Entrez votre email ou numéro de téléphone',
    INVALID_EMAIL_PHONE: 'Email ou numéro de téléphone invalide',
    PASSWORD: 'Mot de passe',
    ENTER_PASSWORD: 'Entrez votre mot de passe',
    INVALID_PASSWORD: 'Mot de passe invalide',
    CONFIRM_PASSWORD: 'Confirmer le mot de passe',
    PASSWORD_DONT_MATCH: 'Mot de passe ne correspond pas',
    SIGNING_IN: 'Connexion en cours',
    FIRST_NAME: 'Prénom',
    LAST_NAME: 'Nom de famille',
    GENDER: 'Sexe',
    DATE_OF_BIRTH: 'Date de naissance',
    ADDRESS: 'Adresse',
    PHONE: 'Numéro de téléphone',
    ENTER_LAST_NAME: 'Entrez votre prénom',
    ENTER_FIRST_NAME: 'Entrez votre nom de famille',
    ENTER_ADDRESS: 'Entrez votre adresse',
    ENTER_PHONE: 'Entrez votre numero de téléphone',
    ENTER_DATE_OF_BIRTH: 'Entrez votre date de naissance',
    SELECT_GENDER: 'Selectionnez votre sexe',
    INVALID_FIRST_NAME: 'Prenom invalide',
    INVALID_LAST_NAME: 'Nom invalide',
    INVALID_ADDRESS: 'Adresse invalide',
    INVALID_PHONE: 'Numero de téléphone invalide',
    EMAIL: 'Email',
    ENTER_EMAIL: 'Entrez votre adresse email',
    INVALID_EMAIL: 'Adresse email non valide',
    ERROR: 'Erreur',
    ALERT: 'Alerte',
    FILL_THE_FORM:
      "S'il vous plaît assurez-vous que vous avez entré et correctement toutes vos informations",
    SIGNING_UP: 'Inscription en cours',
    SIGN_UP_FORM_TITLE: "S'il vous plait remplissez le formulaire",
    CONFIRM_EMAIL: "Confirmer l'email",
    EMAIL_DONT_MATCH: 'Email ne correspond pas',
    NAME: 'Nom',
    INVALID_NAME: 'Nom invalide',
    ENTER_NAME: 'Entrez un nom',
    SPECIALTY: 'Specialité',
    SELECT_SPECIALTY: 'Selectionnez votre specialité',
    INVALID_SPECIALTY: 'Specialité invalide',
    ENTER_LOCATION: 'Précisez votre position',
    BUISNESS_IDENTIFIER: 'Registre de commerce',
    ENTER_BUISNESS_IDENTIFIER: 'Entrez votre registre de commerce',
    INVALID_BUISNESS_IDENTIFIER: 'Registre de commerce invalide',
    SELECT_CITY: 'Selectionnez votre wilaya',
    SELECT_COMMUNE: 'Selectionnez votre commune',
    SELECT_BLOOD_TYPE: 'Selectionnez votre groupe sanguin',
    SIGNING_UP: 'Inscription en cours',
    SIGN_UP_SUCCESSFUL: 'Inscrit avec succès',
    IN_SEARCH_FOR: "En recherche d'un(e)",
    BOOK_APPOINTMENT: 'Prendre un rendez vous',
    NO_RESULTS: 'Pas de resultat trouvés',
    SEARCH: 'Rechercher',
    ERROR_OCCURED: 'Une erreur est suvenue',
    SIGN_OUT: 'Se déconnecter',
    EMAIL_PHONE_IN_USE: 'Adresse mail ou numéro de téléphone déja utilse',
    USER_DOESNT_EXIST: "L'utilisateur n'existe pas",
    WRONG_PASSWORD: 'Mot de passe incorrecte',
    SEARCHING: 'Recherche en cours',
    VIDEO_AVAILABLE: 'Consultation vidéo disponible',
    CONSULTATION_NOT_AVAILABLE: 'Consultations non disponibles',
    MY_APPOINTMENTS: 'Mes rendez vous',
    MY_RELATIVES: 'Mes proches',
    MY_FILES: 'Mes documents',
    PAST: 'Passés',
    COMING: 'Futurs',
    CANCELLED: 'Annulés',
    EDIT: 'Modifier',
    DELETE: 'sipprimer',
    CANCEL: 'Annuler',
    ADD: 'Ajouter',
    ADDING: 'Ajout en cours',
    ADDED_SUCCESSFULY: 'Ajouté avec succès',
    REBOOK_APPOINTMENT: 'Prendre un autre rendez vous',
    PRESCRIPTIONS: 'Ordonnances',
    RECORDS: 'Comptes rendus',
    TEST_RESULTS: 'Resultats des analyses',
    TREATMENTS: 'Traitements',
    BIOLOGY: 'Biologie',
    REPORTS: 'Rapports',
    RADIOLOGY: 'Radiologie',
    VACCINATIONS: 'Vaccination',
    PRESENTATION: 'Présentation',
    PRICING: 'Pricing',
    TELECONSULTATION: 'Téléconsultation',
    CABINET: 'Cabinet',
    EXERCICE_ADDRESS: "Adresse du lieu d'exercice",
    SUNDAY: 'Dimanche',
    MONDAY: 'Lundi',
    TUESDAY: 'Mardi',
    WEDNESDAY: 'Mercredi',
    THURSDAY: 'Jeudi',
    FRIDAY: 'Vendredi',
    SATURDAY: 'Samedi',
    WORKING_DAYS: 'Jours de travail',
    DAY: 'Jour',
    OPENING: 'Ouverture',
    CLOSING: 'Fermeture',
    SELECT_APPOINTMENT_TYPE: 'Selectionnez le type de rendez vous',
    CONTACT_INFORMATIONS: 'Informations de contact',
    SPOKEN_LANGUAGES: 'Langues parlées',
    CONSULTED_BEFORE: 'Est ce que vous etiez deja consulte par ce medecin?',
    YES: 'Oui',
    NO: 'Non',
    COURSES: 'Formations',
    APPOINTMENT_TYPE: 'Type de rendez vous',
    APPOINTMENT_HOUR: 'Heure de rendez vous',
    NO_AVAILABLE_APPOINTMENTS: 'Pas de rendez vous disponibles',
    MY_PATIENTS: 'Mes patients',
    ADD_RELATIVE: 'Ajouter proche',
    ADD_PATIENT: 'Ajouter patient',
    SUBSCRIPTION: 'Abonnement',
    PROFILE: 'Profil',
    ADD_APPOINTMENT: 'Ajouter rendez vous',
    EDIT_SUBSCRIPTION: 'Modifier abonnement',
    EDIT_PROFILE: 'Modifier profil',
    AVAILABLE: 'Disponible',
    MY_INFORMATIONS: 'Mes informations',
    UPDATING: 'Mise a jour en cours',
    UPDATED_SUCCESSFULY: 'Mis a jour avec succès',
    WILAYA: 'Wilaya',
    COMMUNE: 'Commune',
    CONTACT_TEXT:
      "Si vous avez une question contactez nous par email sur l'adresse ",
    SELECT_DOCUMENT_TYPE: 'Selectionnez le type de document',
    DESCRIPTION: 'Description',
    ENTER_DESCRIPTION: 'Entrez une description',
    INVALID_DESCRIPTION: 'Description invalide',
    SELECT_PAYMENT_METHOD: 'Selectionnez une méthode de paiement',
    AMOUNT: 'Montant',
    BALANCE: 'Solde',
    BANK_CARD: 'Carte bancaire',
    SUBSCRIPTION_INFORMATIONS: "Informations sur l'abonnement",
    SUBSCRIPTION_1: 'Planning et gestion des patients',
    SUBSCRIPTION_2: 'Consultation viédo',
    VALIDITY: 'Validité',
    BEGIN_DATE: 'Date debut',
    END_DATE: 'Date fin',
    REMAINING_DAYS: 'Jours restants',
    REMAINING_MINUTES: 'Minutes restantes',
    SESSION_DURATION: 'Durée de séance',
    NOT_SUBSCRIBED: 'Non inscrit',
    BEGIN_APPOINTMENT: 'Demarrer consultation',
    NO_FILES: 'Aucun document trouvé',
    NO_APPOINTMENTS: 'Aucun rendez-vouz trouvé',
    APPOINTMENT_BOOKED: 'Rendez-vous reservé avec succès',
    ENTER_APPOINTMENT_DETAILS: 'Veuillez entrer les détails de rendez-vous ',
  },
  EN: {
    CHOOSE_LANGUAGE: 'Choose your language',
    NEXT: 'Next',
    SLIDE1_TITLE: 'Thousands of doctors',
    SLIDE1_DESCRIPTION:
      'Access thousands of doctors instantly. You can easily contact with the doctors and contact for your needs.',
    SLIDE2_TITLE: 'Live talk with doctors',
    SLIDE2_DESCRIPTION:
      'Easily connect with doctor and start video chat for your better treatment and prescription.',
    SLIDE3_TITLE: 'Video calls with doctors',
    SLIDE3_DESCRIPTION:
      'Book an appointment with doctor.Chat  with doctor via appoinment letter and get a consultation.',
    GET_STARTED: 'Get Started',
    HOME: 'Home',
    SIGN_IN: 'Sign in',
    REGISTER: 'Register',
    LANGUAGE: 'Language',
    LOGIN_AS: 'Login as a',
    REGISTER_AS: 'Register as a',
    PATIENT: 'Patient',
    DOCTOR: 'Doctor',
    PARAMEDICAL: 'Paramedical',
    CLINIC_HOSPITAL: 'Clinic/Hospital',
    LABORATORY: 'Laboratory',
    PHARMACY: 'Pharmacy',
    AMBULANCE: 'Ambulance',
    BLOOD_DONOR: 'Blood Donor',
    PROFESSIONAL: 'Professional',
    WELCOME_BACK: 'Welcome Back!',
    SIGN_IN_TO_CONTINUE: 'Sign in to continue.',
    FORGOT_PASSWORD: 'Forgot password?',
    ABOUT: 'About Us',
    CONTACT: 'Contact Us',
    FOLLOW: 'Follow us on',
    EMAIL_PHONE: 'Email / Phone',
    ENTER_EMAIL_PHONE: 'Enter your email or phone number',
    INVALID_EMAIL_PHONE: 'Invalid email or phone number',
    PASSWORD: 'Password',
    ENTER_PASSWORD: 'Enter your password',
    INVALID_PASSWORD: 'Invalid password',
    CONFIRM_PASSWORD: 'Confirm password',
    PASSWORD_DONT_MATCH: "Passwords don't match",
    SIGNING_IN: 'Signing in',
    FIRST_NAME: 'First name',
    LAST_NAME: 'Last name',
    GENDER: 'Gender',
    DATE_OF_BIRTH: 'Date of birth',
    ADDRESS: 'Address',
    PHONE: 'Phone number',
    EMAIL: 'Email',
    ENTER_EMAIL: 'Enter your email address',
    INVALID_EMAIL: 'Invalid email address',
    CONFIRM_EMAIL: 'Confirm your email',
    EMAIL_DONT_MATCH: "Emails don't match",
    NAME: 'Name',
    INVALID_NAME: 'Invalid name',
    ENTER_NAME: 'Enter a name',
    SPECIALTY: 'Speciality',
    SELECT_SPECIALTY: 'Select your speciality',
    INVALID_SPECIALTY: 'Invalid speciality',
    ENTER_LOCATION: 'Select your location',
    BUISNESS_IDENTIFIER: 'Buisness identifier',
    ENTER_BUISNESS_IDENTIFIER: 'Enter your buisness identifier',
    INVALID_BUISNESS_IDENTIFIER: 'Invalid buisness identifier',
    SELECT_CITY: 'Select your city',
    SELECT_COMMUNE: 'Select your commune',
    SELECT_BLOOD_TYPE: 'Select your blood type',
    SIGNING_UP: 'Signing you up',
    SIGN_UP_SUCCESSFUL: 'Signed up successfully',
    IN_SEARCH_FOR: 'In search for',
    BOOK_APPOINTMENT: 'Book appointment',
    NO_RESULTS: 'No results found',
    SEARCH: 'Search',
    ERROR_OCCURED: 'An error has occured',
    SIGN_OUT: 'Sign out',
    EMAIL_PHONE_IN_USE: 'Email or phone already in use',
    USER_DOESNT_EXIST: "User doesn't exist",
    WRONG_PASSWORD: 'Wrong password',
    SEARCHING: 'Searching',
    VIDEO_AVAILABLE: 'Video consultation available',
    CONSULTATION_NOT_AVAILABLE: 'Consultation not available',
    MY_APPOINTMENTS: 'My appointments',
    MY_RELATIVES: 'My relatives',
    MY_FILES: 'My files',
    PAST: 'Past',
    COMING: 'Coming',
    CANCELLED: 'Cancelled',
    EDIT: 'Edit',
    DELETE: 'Delete',
    CANCEL: 'Cancel',
    ADD: 'Add',
    ADDING: 'Adding',
    ADDED_SUCCESSFULY: 'Added successfuly',
    REBOOK_APPOINTMENT: 'Book another appointment',
    PRESCRIPTIONS: 'Prescriptions',
    RECORDS: 'Records',
    TEST_RESULTS: 'Test results',
    TREATMENTS: 'Treatments',
    BIOLOGY: 'Biology',
    REPORTS: 'Reports',
    RADIOLOGY: 'Radiology',
    VACCINATIONS: 'Vaccination',
    PRESENTATION: 'Presentation',
    PRICING: 'Pricing',
    TELECONSULTATION: 'Teleconsultation',
    CABINET: 'Cabinet',
    EXERCICE_ADDRESS: 'Exercice address',
    SUNDAY: 'Sunday',
    MONDAY: 'Monday',
    TUESDAY: 'Tuesday',
    WEDNESDAY: 'Wednesday',
    THURSDAY: 'Thursday',
    FRIDAY: 'Friday',
    SATURDAY: 'Saturday',
    WORKING_DAYS: 'Working days',
    DAY: 'Day',
    OPENING: 'Opening',
    CLOSING: 'Closing',
    SELECT_APPOINTMENT_TYPE: 'Select appointment type',
    CONTACT_INFORMATIONS: 'Contact informations',
    SPOKEN_LANGUAGES: 'Spoken languages',
    CONSULTED_BEFORE: 'Have you been consulted by this doctor?',
    YES: 'Yes',
    NO: 'No',
    COURSES: 'Courses',
    APPOINTMENT_TYPE: 'Appointment type',
    APPOINTMENT_HOUR: 'Appointment hour',
    NO_AVAILABLE_APPOINTMENTS: 'No available appointments',
    MY_PATIENTS: 'My patients',
    ADD_RELATIVE: 'Add relative',
    ADD_PATIENT: 'Add patient',
    SUBSCRIPTION: 'Subscription',
    PROFILE: 'Profile',
    ADD_APPOINTMENT: 'Add appointment',
    EDIT_SUBSCRIPTION: 'Edit subscription',
    EDIT_PROFILE: 'Edit profile',
    AVAILABLE: 'Available',
    MY_INFORMATIONS: 'My informations',
    UPDATING: 'Updating',
    UPDATED_SUCCESSFULY: 'Updated successfuly',
    WILAYA: 'Wilaya',
    COMMUNE: 'Commune',
    CONTACT_TEXT:
      'If you have a question contact us in the email address below',
    SELECT_DOCUMENT_TYPE: 'Select document type',
    DESCRIPTION: 'Description',
    ENTER_DESCRIPTION: 'Enter description',
    INVALID_DESCRIPTION: 'Invalid description',
    SELECT_PAYMENT_METHOD: 'Select a payment method',
    AMOUNT: 'Amount',
    BALANCE: 'Balance',
    BANK_CARD: 'Bank card',
    SUBSCRIPTION_INFORMATIONS: 'Subscription informations',
    SUBSCRIPTION_1: 'Planning and patients managment',
    SUBSCRIPTION_2: 'Video consultation',
    VALIDITY: 'Validity',
    BEGIN_DATE: 'Begin date',
    END_DATE: 'End date',
    REMAINING_DAYS: 'Remaining days',
    REMAINING_MINUTES: 'Remaining minutes',
    SESSION_DURATION: 'Session duration',
    NOT_SUBSCRIBED: 'Not subscribed',
    BEGIN_APPOINTMENT: 'Begin appointment',
    NO_FILES: 'No files found',
    NO_APPOINTMENTS: 'No appointments found',
    APPOINTMENT_BOOKED: 'Appointment booked successfuly',
    ENTER_APPOINTMENT_DETAILS: 'Enter all appointment details',
  },
};
