export const USER_ROLES = {
  PATIENT: 'PATIENT',
  DOCTOR: 'DOCTOR',
  PARAMEDICAL: 'PARAMEDICAL',
  CLINIC_HOSPITAL: 'CLINIC_HOSPITAL',
  LABORATORY: 'LABORATORY',
  PHARMACY: 'PHARMACY',
  AMBULANCE: 'AMBULANCE',
  BLOOD_DONOR: 'BLOOD_DONOR',
};
