export const APPLICATION_STATE_ACTIONS = {
  GET_APPLICATION: 'GET_APPLICATION',
  SET_APPLICATION: 'SET_APPLICATION',
};

export const USER_STATE_ACTIONS = {
  USER_STATE_CHANGE: 'USER_STATE_CHANGE',
  USER_SIGN_OUT: 'USER_SIGN_OUT',
  USER_SIGN_IN: 'USER_SIGN_IN',
  USER_LOADING: 'USER_LOADING',
  USER_UPDATE: 'USER_UPDATE',
  SET_ROLE: 'SET_ROLE',
  GET_ROLE: 'GET_ROLE',
  SET_TOKEN: 'SET_TOKEN',
  GET_TOKEN: 'GET_TOKEN',
};

export const CALL_STATE_ACTIONS = {
  GET_CALL: 'GET_CALL',
  SET_CALL: 'SET_CALL',
};